In [1]:
import tensorflow as tf
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])

In [2]:
t.shape

TensorShape([2, 3])

In [3]:
t.dtype

tf.float32

In [4]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [5]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [6]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [7]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [8]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [9]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(t))+10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [10]:
import numpy as np
a = np.array([2.,4.,5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [11]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [12]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [13]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [14]:
# error in type conversions
tf.constant(2.)+tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

In [15]:
# if we need to convert types we can use cast method
t2 = tf.constant(40.,dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [16]:
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])

In [17]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [18]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [19]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing(as_frame=True)

In [20]:
X =housing.data

In [21]:
y=housing.target

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
def huber_fn(y_true,y_pred):
  error = y_true-y_pred
  is_small_error = tf.abs(error)<1
  squared_loss = tf.square(error)/2
  linear_loss = tf.abs(error) - 0.5
  return tf.where(is_small_error,squared_loss,linear_loss)

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss=huber_fn, metrics=['mae'])

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [28]:
model.fit(x_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

Epoch 1/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 1s 609us/step - loss: 0.4239 - mae: 0.7593 - val_loss: 0.1906 - val_mae: 0.4689
Epoch 2/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - loss: 0.1729 - mae: 0.4413 - val_loss: 0.1765 - val_mae: 0.4425
Epoch 3/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - loss: 0.1613 - mae: 0.4257 - val_loss: 0.1637 - val_mae: 0.4232
Epoch 4/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - loss: 0.1460 - mae: 0.4015 - val_loss: 0.1597 - val_mae: 0.4151
Epoch 5/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 0.1469 - mae: 0.3988 - val_loss: 0.1542 - val_mae: 0.4011
Epoch 6/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - loss: 0.1383 - mae: 0.3869 - val_loss: 0.1502 - val_mae: 0.3981
Epoch 7/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - loss: 0.1389 - mae: 0.3868 - val_loss: 0.1462 - val_mae: 0.3943
Epoch 8/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - loss: 0.1326 - mae: 0.3776 - val_loss: 0.1431 - val_mae: 0.3882
Epoch 9/50
465/465 ━━━━━━━━━━━━━━━━━━━━ 

In [29]:
# for a different threshold
def create_huber(threshold=1.0):
  def hubber(y_true,y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error)<threshold
    squared_loss = tf.square(error)/2
    linear_loss = threshold * tf.abs(error) - threshold**2/2
    return tf.where(is_small_error,squared_loss,linear_loss)
  return hubber

In [30]:
# if you need to save a threshold with the model
# you need to create a subclass of keras.losses.Loss class


class HubberLoss(keras.losses.Loss):
  def __init__(self,threshold=1.0,**kwargs):
    self.threshold = threshold
    super().__init__(**kwargs)
  def call(self,y_true,y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error)<self.threshold
    squared_loss = tf.square(error)/2
    linear_loss = self.threshold*tf.abs(error) - self.threshold**2/2
    return tf.where(is_small_error,squared_loss,linear_loss)
  def get_config(self):
    base_config = super().get_config()
    return {**base_config,"threshold":self.threshold}

In [31]:
def my_softplus(z):
  return tf.math.log(tf.exp(z)+1.0)

In [32]:
def my_glorot_initializer(shape,dtype=tf.float32):
  stddev = tf.sqrt(2./shape[0]+shape[1])
  return tf.random.normal(shape,stddev=stddev,dtype=dtype)

In [33]:
def my_l1_regularizer(weights):
  return tf.reduce_sum(tf.abs(0.01*weights))

In [34]:
def my_positive_weights(weights):
  return tf.where(weights<0.,tf.zeros_like(weights),weights)

In [35]:
layer = keras.layers.Dense(30,activation=my_softplus,
                           kernel_initializer = my_glorot_initializer,
                           kernel_constraint=my_positive_weights)

In [36]:
class MyL1Regularizer(keras.regularizers.Regularizer):
  def __init__(self,factor):
    self.factor = factor
  def __call__(self,weights):
    return tf.reduce_sum(tf.abs(self.factor*weights))
  def get_config(self):
    return {"factor":self.factor}